### ISSUE TITLE
Images issue

### ISSUE THREAD

**Issue by fdcoder81** [mwieth/Webpack-4-boilerplate#5]
Hi,

I'm using this great webpack boilerplate but I have a problem with images.
How can I use them in dev mode?
I copy the logo in the src dir and on my html I try these:
`<img src="logo.png" alt="" />`
`<img src="./logo.png" alt="" />`
But no image appear on localhost live dev.

Thanks

**Comment by mwieth** [comment]
Hi,

as of this moment you can't load images while including them in your html as img element as webpack out of the box only understands javascript.

However you have 2 options:
Option 1 do it with javascript: 
```
import logo from './logo.png';

const img = document.createElement("img");
img.src = logo;
img.width = 32;
document.body.appendChild(img);
```

Option 2 as background image: 
```
background-image: url('../logo.png')
background-size: contain;
background-repeat: no-repeat;
```

I will try to support this in the future most likely by adding the html-loader (https://github.com/webpack-contrib/html-loader). 

Best regards

**Comment by fdcoder81** [comment]
ok,
Thank you very much!
