### ISSUE TITLE
Vendor chunk url not output in html file

### ISSUE THREAD

**Issue by rjbultitude** [mwieth/Webpack-4-boilerplate#7]
When any external modules such as packages in `node_modules` are bundled a vendor chunk is created, but there's no url for the vendor file in the resulting html - the href value is simply empty i.e. `<script defer src=""></script>`

To recreate this issue install a module such as lodash, import it into index.js, run `npm run build:prod` and inspect the index.html file in the dist folder.

**Comment by mwieth** [comment]
Everything you import in index.js will be in the concatenated `main.[chunkhash].js` file. So the code from your external module(i.e lodash) should be there. If you want an additional vendor script file you would have to define an additional entry point like this:

webpack.prod.js:
```
  entry: {
    vendor: 'lodash',
    main: './' + src_Path + '/index.js',
  },
```

index.html:
```
<script defer src="<%= htmlWebpackPlugin.files.chunks.vendor.entry %>"></script>
<script defer src="<%= htmlWebpackPlugin.files.chunks.main.entry %>"></script>
```
Now you should have a `vendor.js` which contains the lodash code (don't forget load order is important). Does this help you?

**Comment by rjbultitude** [comment]
Yes, thanks. I thought it was the intention to have a vendor chunk, but I was mistaken
